---
abstract: 'Build a distribution with a bootstrapped version of itself.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-App-Command-self
provides:
  Dist::Zilla::App::Command::self:
    file: lib/Dist/Zilla/App/Command/self.pm
    version: '0.001004'
recommends:
  Path::Tiny: '0.058'
requires:
  Carp: '0'
  Dist::Zilla::App: '0'
  File::pushd: '0'
  Path::Tiny: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-App-Command-self/issues
  homepage: https://github.com/kentnl/Dist-Zilla-App-Command-self
  repository: https://github.com/kentnl/Dist-Zilla-App-Command-self.git
version: '0.001004'
